In [458]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

In [459]:
# Set year of desired dataset
year = 2023

In [460]:
# create beautifulSoup object for passing
url = "https://www.pro-football-reference.com/years/{}/passing.htm".format(year)
html = urlopen(url)
soup = BeautifulSoup(html)

# get header data
headers = [th.getText() for th in soup.findAll('tr')[0].findAll('th')]
headers = headers[1:]


# get table row data
rows = soup.findAll('tr', class_ = lambda table_rows: table_rows != "thead")
player_stats = [[td.getText() for td in rows[i].findAll('td')]
                for i in range(len(rows))]
player_stats = player_stats[2:]

# create pandas DataFrame object
pass_stats = pd.DataFrame(player_stats, columns = headers)

# drop unnecessary columns
pass_stats = pass_stats.drop(['QBrec', '1D', 'Lng', 'Succ%'], axis=1)
pass_stats = pass_stats.drop(pass_stats.columns[-4:], axis=1) # drop last 4 columns
pass_stats = pass_stats.drop(pass_stats.columns[-2], axis=1) # drop yards lost to sack column
pass_stats = pass_stats.drop(pass_stats.columns[1:6], axis=1) # drop all repeating stats but name

# adjust column headers to be more descriptive
pass_stats = pass_stats.rename(columns={'Att' : 'PassAtt'   , 
                                        'Yds' : 'PassYds'   , 
                                        'TD'  : 'PassTD'    ,
                                        'Y/A' : 'PassYds/A' ,
                                        'Y/G' : 'PassYds/G'  })



pass_stats.head()

,Player,Cmp,PassAtt,Cmp%,PassTD,TD%,Int,Int%,PassYds/A,AY/A,Y/C,PassYds/G,Rate,QBR,Sk,Sk%
0,Jared Goff,407,605,67.3,30,5.0,12,2.0,7.6,7.7,11.2,269.1,97.9,60.3,30,4.7
1,Dak Prescott*,410,590,69.5,36,6.1,9,1.5,7.7,8.2,11.0,265.6,105.9,72.7,39,6.2
2,Josh Allen,385,579,66.5,29,5.0,18,3.1,7.4,7.0,11.2,253.3,92.2,69.6,24,4.0
3,Brock Purdy*,308,444,69.4,31,7.0,11,2.5,9.6,9.9,13.9,267.5,113.0,72.8,28,5.9
4,Patrick Mahomes*,401,597,67.2,27,4.5,14,2.3,7.0,6.9,10.4,261.4,92.6,63.1,27,4.3

In [461]:
# create beautifulSoup object for rushing
url = "https://www.pro-football-reference.com/years/{}/rushing.htm".format(year)
html = urlopen(url)
soup = BeautifulSoup(html)

# get header data
headers = [th.getText() for th in soup.findAll('tr')[1].findAll('th')]
headers = headers[1:]
# adjust column headers to be more descriptive

# get table row data
rows = soup.findAll('tr', class_ = lambda table_rows: table_rows != "thead")
player_stats = [[td.getText() for td in rows[i].findAll('td')]
                for i in range(len(rows))]
player_stats = player_stats[2:]

# create pandas DataFrame object
rush_stats = pd.DataFrame(player_stats, columns = headers)

# drop unnecessary columns
rush_stats = rush_stats.drop(['1D', 'Lng', 'Succ%'], axis=1)
rush_stats = rush_stats.drop(rush_stats.columns[1:6], axis=1) # drop all repeating stats but name
rush_stats = rush_stats.drop(rush_stats.columns[-1], axis=1) #remove fumbles

# adjust column headers to be more descriptive
rush_stats = rush_stats.rename(columns={'Att' : 'RushAtt'   , 
                                        'Yds' : 'RushYds'   , 
                                        'TD'  : 'RushTD'    ,
                                        'Y/A' : 'RushYds/A' ,
                                        'Y/G' : 'RushYds/G'  })

rush_stats.head()

                  Player RushAtt RushYds RushTD RushYds/A RushYds/G
0         Derrick Henry*     280    1167     12       4.2      68.6
1  Christian McCaffrey*+     272    1459     14       5.4      91.2
2          Rachaad White     272     990      6       3.6      58.2
3         Travis Etienne     267    1008     11       3.8      59.3
4              Joe Mixon     257    1034      9       4.0      60.8

In [462]:
# create beautifulSoup object for receiving
url = "https://www.pro-football-reference.com/years/{}/receiving.htm".format(year)
html = urlopen(url)
soup = BeautifulSoup(html)

# get header data
headers = [th.getText() for th in soup.findAll('tr')[0].findAll('th')]
headers = headers[1:]
# adjust column headers to be more descriptive

# get table row data
rows = soup.findAll('tr', class_ = lambda table_rows: table_rows != "thead")
player_stats = [[td.getText() for td in rows[i].findAll('td')]
                for i in range(len(rows))]
player_stats = player_stats[2:]

# create pandas DataFrame object
rec_stats = pd.DataFrame(player_stats, columns = headers)

# drop unnecessary columns
rec_stats = rec_stats.drop(['1D', 'Lng', 'Succ%'], axis=1)
rec_stats = rec_stats.drop(rec_stats.columns[1:6], axis=1) # drop all repeating stats but name
rec_stats = rec_stats.drop(rec_stats.columns[-1], axis=1) #remove fumbles

# adjust column headers to be more descriptive
rec_stats = rec_stats.rename(columns={'Yds' : 'RecYds'   , 
                                        'TD'  : 'RecTD'    ,
                                        'Y/G' : 'RecYds/G'  })

rec_stats.head()

                Player  Tgt  Rec  Ctch% RecYds   Y/R RecTD Y/Tgt  R/G RecYds/G
0        Tyreek Hill*+  171  119  69.6%   1799  15.1    13  10.5  7.4    112.4
1  Amon-Ra St. Brown*+  164  119  72.6%   1515  12.7    10   9.2  7.4     94.7
2         Evan Engram*  143  114  79.7%    963   8.4     4   6.7  6.7     56.6
3  Michael Pittman Jr.  156  109  69.9%   1152  10.6     4   7.4  6.8     72.0
4        Keenan Allen*  150  108  72.0%   1243  11.5     7   8.3  8.3     95.6

In [463]:
# create beautifulSoup object for total scrimmage yards
url = "https://www.pro-football-reference.com/years/{}/scrimmage.htm".format(year)
html = urlopen(url)
soup = BeautifulSoup(html)

# get header data
headers = [th.getText() for th in soup.findAll('tr')[1].findAll('th')]
headers = headers[1:]
# adjust column headers to be more descriptive

# get table row data
rows = soup.findAll('tr', class_ = lambda table_rows: table_rows != "thead")
player_stats = [[td.getText() for td in rows[i].findAll('td')]
                for i in range(len(rows))]
player_stats = player_stats[2:]

# create pandas DataFrame object
scrim_stats = pd.DataFrame(player_stats, columns = headers)

# drop unnecessary columns
scrim_stats = scrim_stats.drop(['Succ%'], axis=1)
scrim_stats = scrim_stats.drop(scrim_stats.columns[1:-6], axis=1) #take first and last few columns
scrim_stats = scrim_stats.drop(scrim_stats.columns[-1], axis=1) #remove fumbles

scrim_stats.head()

                  Player   A/G Touch Y/Tch  YScm RRTD
0  Christian McCaffrey*+  17.0   339   6.0  2023   21
1          CeeDee Lamb*+   0.8   149  12.5  1862   14
2          Tyreek Hill*+   0.4   125  14.5  1814   13
3            Breece Hall  13.1   299   5.3  1585    9
4            Puka Nacua*   0.7   117  13.5  1575    6

In [464]:
# create beautifulSoup object for fantasy stats
url = "https://www.pro-football-reference.com/years/{}/fantasy.htm".format(year)
html = urlopen(url)
soup = BeautifulSoup(html)

# get header data
headers = [th.getText() for th in soup.findAll('tr')[1].findAll('th')]
headers = headers[1:]
# adjust column headers to be more descriptive

# get table row data
rows = soup.findAll('tr', class_ = lambda table_rows: table_rows != "thead")
player_stats = [[td.getText() for td in rows[i].findAll('td')]
                for i in range(len(rows))]
player_stats = player_stats[2:]

# create pandas DataFrame object
fantasy_stats = pd.DataFrame(player_stats, columns = headers)

# drop unnecessary columns
fantasy_stats = fantasy_stats.drop(fantasy_stats.columns[4:-7], axis=1) #take first and last few columns

# adjust column headers to be more descriptive
fantasy_stats = fantasy_stats.rename(columns={'FantPos' : 'Pos'})

fantasy_stats.head()

,Player,Tm,Pos,Age,FantPt,PPR,DKPt,FDPt,VBD,PosRank,OvRank
0,Christian McCaffrey*+,SFO,RB,27,324,391.3,399.3,357.8,157,1,1
1,CeeDee Lamb*+,DAL,WR,24,268,403.2,411.2,335.7,131,1,2
2,Josh Allen,BUF,QB,27,393,392.6,420.6,410.6,122,1,3
3,Tyreek Hill*+,MIA,WR,29,257,376.4,380.4,316.9,120,2,4
4,Jalen Hurts*,PHI,QB,25,357,356.8,382.8,371.8,89,2,5

In [465]:
# combine all data
stats = pd.merge(fantasy_stats, pass_stats, on='Player', how='outer')
stats = pd.merge(stats, rush_stats, on='Player', how='outer')
stats = pd.merge(stats, rec_stats, on='Player', how='outer')
stats = pd.merge(stats, scrim_stats, on='Player', how='outer')
stats.head()

,Player,Tm,Pos,Age,FantPt,PPR,DKPt,FDPt,VBD,PosRank,...,Y/R,RecTD,Y/Tgt,R/G,RecYds/G,A/G,Touch,Y/Tch,YScm,RRTD
0,A.J. Brown*,PHI,WR,26,184,289.6,294.6,236.6,51,8,...,13.7,7,9.2,6.2,85.6,,106,13.7,1456,7
1,A.J. McCarron,CIN,QB,33,1,0.8,0.8,0.8,,74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A.T. Perry,NOR,WR,24,49,60.6,63.6,54.6,,85,...,20.5,4,13.7,1.2,24.6,,12,20.5,246,4
3,AJ Dillon,GNB,RB,25,96,117.6,123.6,106.6,,40,...,10.1,0,8.0,1.5,14.9,11.9,200,4.2,836,2
4,Aaron Jones,GNB,RB,29,105,134.9,141.9,119.9,,36,...,7.8,1,5.4,2.7,21.2,12.9,172,5.2,889,3

In [467]:
# convert all cells that should be numbers from strings to numbers
columns_to_convert = stats.columns[3:]  # Adjusted index to start from column 3

# convert selected columns to numeric type
for col in columns_to_convert:
    stats[col] = pd.to_numeric(stats[col], errors='coerce')

# fix duplicated players
stats.drop_duplicates('Player', inplace=True)

# data manipulation
stats = stats.replace(r'', 0, regex=True) # replace empty columns with zero
stats = stats.fillna(0)
stats = stats.replace(r'\+|\*', '', regex=True) # remove trailing + and * from names

stats.head()

,Player,Tm,Pos,Age,FantPt,PPR,DKPt,FDPt,VBD,PosRank,...,Y/R,RecTD,Y/Tgt,R/G,RecYds/G,A/G,Touch,Y/Tch,YScm,RRTD
0,A.J. Brown,PHI,WR,26.0,184.0,289.6,294.6,236.6,51.0,8.0,...,13.7,7.0,9.2,6.2,85.6,0.0,106.0,13.7,1456.0,7.0
1,A.J. McCarron,CIN,QB,33.0,1.0,0.8,0.8,0.8,0.0,74.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,A.T. Perry,NOR,WR,24.0,49.0,60.6,63.6,54.6,0.0,85.0,...,20.5,4.0,13.7,1.2,24.6,0.0,12.0,20.5,246.0,4.0
3,AJ Dillon,GNB,RB,25.0,96.0,117.6,123.6,106.6,0.0,40.0,...,10.1,0.0,8.0,1.5,14.9,11.9,200.0,4.2,836.0,2.0
4,Aaron Jones,GNB,RB,29.0,105.0,134.9,141.9,119.9,0.0,36.0,...,7.8,1.0,5.4,2.7,21.2,12.9,172.0,5.2,889.0,3.0

In [468]:
stats.to_csv('{}playerstats.csv'.format(year)) # csv output format {year}playerstats.csv

In [469]:
stats.drop(stats[stats['Pos'] != 'WR'].index)

,Player,Tm,Pos,Age,FantPt,PPR,DKPt,FDPt,VBD,PosRank,...,Y/R,RecTD,Y/Tgt,R/G,RecYds/G,A/G,Touch,Y/Tch,YScm,RRTD
0,A.J. Brown,PHI,WR,26.0,184.0,289.6,294.6,236.6,51.0,8.0,...,13.7,7.0,9.2,6.2,85.6,0.0,106.0,13.7,1456.0,7.0
2,A.T. Perry,NOR,WR,24.0,49.0,60.6,63.6,54.6,0.0,85.0,...,20.5,4.0,13.7,1.2,24.6,0.0,12.0,20.5,246.0,4.0
7,Adam Thielen,CAR,WR,33.0,128.0,231.0,234.0,179.5,0.0,31.0,...,9.8,4.0,7.4,6.1,59.6,0.1,104.0,9.8,1020.0,4.0
12,Alec Pierce,IND,WR,23.0,63.0,95.4,98.4,79.4,0.0,68.0,...,16.1,2.0,7.9,1.9,30.2,0.0,32.0,16.1,514.0,2.0
14,Alex Erickson,LAC,WR,31.0,29.0,45.2,48.2,37.2,0.0,114.0,...,14.5,1.0,8.0,2.0,29.0,0.0,16.0,14.5,232.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,Xavier Gipson,NYJ,WR,22.0,38.0,58.7,63.7,48.2,0.0,98.0,...,10.9,0.0,6.0,1.2,13.5,0.5,29.0,10.2,297.0,1.0
645,Xavier Hutchinson,HOU,WR,23.0,14.0,21.9,21.9,17.9,0.0,150.0,...,11.3,0.0,4.7,0.5,5.6,0.3,13.0,10.7,139.0,0.0
651,Zach Pascal,ARI,WR,29.0,2.0,5.9,5.9,3.9,0.0,191.0,...,4.8,0.0,1.3,0.3,1.4,0.0,4.0,4.8,19.0,0.0
656,Zay Flowers,BAL,WR,23.0,129.0,206.4,209.4,167.9,0.0,30.0,...,11.1,5.0,7.9,4.8,53.6,0.5,85.0,10.8,914.0,6.0
657,Zay Jones,JAX,WR,28.0,44.0,78.1,81.1,61.1,0.0,91.0,...,9.4,2.0,5.0,3.8,35.7,0.0,34.0,9.4,321.0,2.0